In [2]:
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(v1)
print(v2)

[1 2 3]
[4 5 6]


In [5]:
v_add = v1 + v2
v_sub = v1 - v2

In [6]:
print(v_add, v_sub)

[5 7 9] [-3 -3 -3]


In [9]:
scalar = 2
v_scale = v1 * scalar
print(v_scale)

[2 4 6]


In [10]:
dot_product = np.dot(v1, v2)
print (dot_product)

32


In [12]:
magnitude_v1 = np.linalg.norm(v1)
print (magnitude_v1)

3.7416573867739413


In [19]:
A = np.array([[1,2,3], [4,5,6]])
print (A)

B= np.array([[7,8,9], [10,11,12], [13,14,15]])
print(B)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [25]:
C = np.array([[1,2,3], [4,5,6]])
matrix_add = A +C
matrix_sub = A - C

print("A + C =\n", matrix_add)
print("A - C =\n", matrix_sub)

A + C =
 [[ 2  4  6]
 [ 8 10 12]]
A - C =
 [[0 0 0]
 [0 0 0]]


In [27]:
matrix_mul = np.dot(A,B)
print(matrix_mul)

[[ 66  72  78]
 [156 171 186]]


In [33]:
A = np.array([[2,1], [1,2]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [35]:
A = np.array([[4,7], [2,6]])
A_inv = np.linalg.inv(A)
print(A)
print(A_inv)

[[4 7]
 [2 6]]
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [36]:
identity = np.dot(A, A_inv)
print (identity)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [ ]:
1 0 0
0 1 0
0 0 1